"""empty message

Revision ID: 290dcf8dae79
Revises: 69749b3ed837
Create Date: 2021-10-31 23:15:41.634860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290dcf8dae79'
down_revision = '69749b3ed837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('icon', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'icon')
    # ### end Alembic commands ###
